export type Row={id:string;kind:string;data:Record<string,any>;createdAt:string;updatedAt:string};
export type Field={key:string;label:string;type?:string;options?:string[];required?:boolean};
export const mileageTypes=['Showing','Meeting','Training','Transaction','Contact','Activity','Other'];
export function mileageMatches(type:string,row:Row){
 const kinds:Record<string,string>={Showing:'showing',Meeting:'note',Training:'note',Transaction:'transaction',Contact:'contact',Activity:'note',Other:'note'};
 return kinds[type]===row.kind&&(!['Meeting','Training'].includes(type)||row.data.type===type);
}
export function checkMileageAttachment(data:Record<string,any>,row:Row|null){
 if(data.linkedId&&(!row||!mileageMatches(data.linkedType,row)))throw Error('Choose a matching record for this business activity.');
}
export const stages=['Prospecting','Active','Under contract','Closing','Closed','Cancelled'];
export const definitions:Record<string,{name:string;plural:string;fields:Field[]}>= {
contact:{name:'contact',plural:'Contacts',fields:[{key:'name',label:'Full name',required:true},{key:'email',label:'Email',type:'email'},{key:'phone',label:'Phone',type:'tel'},{key:'type',label:'Relationship',options:['Lead','Buyer','Seller','Buyer & seller','Past client','Vendor','Other']},{key:'status',label:'Status',options:['New','Active','Nurture','Past client','Archived']},{key:'source',label:'Source',options:['Manual','Referral','BoldTrail','Follow Up Boss','Zillow','Realtor.com','Website','Facebook','Other']},{key:'followUp',label:'Next follow-up',type:'date'},{key:'notes',label:'Notes',type:'textarea'}]},
transaction:{name:'transaction',plural:'Transactions',fields:[{key:'name',label:'Property address',required:true},{key:'contactId',label:'Client',type:'contact',required:true},{key:'side',label:'Representation',options:['Buyer','Seller','Both']},{key:'status',label:'Stage',options:stages},{key:'price',label:'Purchase price ($)',type:'money'},{key:'commission',label:'Commission amount ($)',type:'money'},{key:'date',label:'Closing date',type:'date'},{key:'notes',label:'Notes',type:'textarea'}]},
task:{name:'task',plural:'Tasks',fields:[{key:'name',label:'Task',required:true},{key:'date',label:'Due date',type:'date'},{key:'priority',label:'Priority',options:['Normal','High','Low']},{key:'status',label:'Status',options:['Open','Complete']},{key:'transactionId',label:'Transaction',type:'transaction'},{key:'contactId',label:'Contact',type:'contact'},{key:'notes',label:'Notes',type:'textarea'}]},
showing:{name:'showing',plural:'Showings',fields:[{key:'name',label:'Property address',required:true},{key:'contactId',label:'Client',type:'contact'},{key:'date',label:'Date',type:'date',required:true},{key:'time',label:'Time (your local time)',type:'time'},{key:'status',label:'Status',options:['Scheduled','Completed','Cancelled']},{key:'notes',label:'Access instructions / feedback',type:'textarea'}]},
expense:{name:'expense',plural:'Expenses',fields:[{key:'name',label:'Vendor / description',required:true},{key:'amount',label:'Amount ($)',type:'money',required:true},{key:'date',label:'Date',type:'date',required:true},{key:'category',label:'Category',options:['Advertising','MLS & dues','Software','Office','Photography','Education','Travel','Meals','Other']},{key:'status',label:'Deductibility',options:['Needs review','Deductible','Not deductible']},{key:'businessUse',label:'Business use (%)',type:'percent'},{key:'transactionId',label:'Transaction',type:'transaction'},{key:'notes',label:'Notes',type:'textarea'}]},
mileage:{name:'mileage entry',plural:'Mileage',fields:[{key:'name',label:'Business purpose',required:true},{key:'date',label:'Date',type:'date',required:true},{key:'from',label:'From',required:true},{key:'to',label:'To',required:true},{key:'miles',label:'Miles',type:'number',required:true},{key:'linkedType',label:'Business activity',options:['',...mileageTypes]},{key:'linkedId',label:'Attached record',type:'linked'},{key:'activityName',label:'Activity name'},{key:'notes',label:'Notes',type:'textarea'}]},
note:{name:'activity',plural:'Activity',fields:[{key:'name',label:'Activity / note',required:true},{key:'type',label:'Type',options:['Note','Call','Email','Text','Meeting','Training','Open house','Inspection','Other']},{key:'date',label:'Date',type:'date'},{key:'contactId',label:'Contact',type:'contact'},{key:'transactionId',label:'Transaction',type:'transaction'},{key:'notes',label:'Details',type:'textarea'}]},
};
export function validate(kind:string,input:unknown){const def=definitions[kind];if(!def||!input||typeof input!=='object'||Array.isArray(input))throw Error('Invalid record.');const data:Record<string,any>={};for(const f of def.fields){let v=(input as any)[f.key]??'';if(typeof v!=='string'&&typeof v!=='number')throw Error(`Invalid ${f.label}.`);v=String(v).trim();if(f.required&&!v)throw Error(`${f.label} is required.`);if(v.length>(f.type==='textarea'?20000:500))throw Error(`${f.label} is too long.`);if(v&&f.options&&!f.options.includes(v))throw Error(`Invalid ${f.label}.`);if(v&&f.type==='date'&&(!/^\d{4}-\d{2}-\d{2}$/.test(v)||!Number.isFinite(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v))throw Error('Enter a valid date.');if(v&&f.type==='time'&&!/^([01]\d|2[0-3]):[0-5]\d$/.test(v))throw Error('Enter a valid time.');if(v&&f.type==='email'&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(v))throw Error('Enter a valid email.');if(v&&['money','number','percent'].includes(f.type||'')){if(!Number.isFinite(Number(v))||Number(v)<0||Number(v)>1e12||(f.type==='percent'&&Number(v)>100))throw Error(`Invalid ${f.label}.`);v=f.type==='money'?Math.round(Number(v)*100):Number(v);}data[f.key]=v;}return data;}
export function localDay(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
export function money(cents:any){return new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(Number(cents||0)/100);}
export function displayDate(v:string){return v?new Date(v+'T12:00:00').toLocaleDateString('en-US',{month:'short',day:'numeric',year:'numeric'}):'No date';}
